import { fetchApi } from './api.service';

// services/analytics.service.ts

// Define the data structure for a learner's progress, which will be returned by our service.
export type CourseProgress = {
  courseId: number;
  courseTitle: string;
  courseOverallProgress: number; // Percentage for this specific course
  chaptersCompleted: number;
  totalChapters: number;
};

export type LearnerProgress = {
  id: string
  name: string
  email: string
  coursesEnrolled: number
  coursesCompleted: number
  overallProgress: number // a percentage from 0 to 100
  courses: CourseProgress[]; // New field for detailed course progress
}

// Type for the dashboard summary data from the API
export type AdminDashboardSummary = {
  totalUsers: number;
  totalCourses: number;
  totalQuizAttemptsGlobal: number;
  totalCertificatesGlobal: number;
  mode: "ADMIN";
}

// Mock data that simulates a complex backend aggregation.
// In a real application, this data would be generated by a single API endpoint
// that joins users, orders, courses, and chapter completion records.
const mockData: LearnerProgress[] = [
  { 
    id: "usr_1", 
    name: "Alice Dupont", 
    email: "alice.dupont@example.com", 
    coursesEnrolled: 3, 
    coursesCompleted: 1, 
    overallProgress: 40,
    courses: [
      { courseId: 101, courseTitle: "Introduction au Dev Web", courseOverallProgress: 75, chaptersCompleted: 3, totalChapters: 4 },
      { courseId: 102, courseTitle: "Bases de Python", courseOverallProgress: 20, chaptersCompleted: 1, totalChapters: 5 },
      { courseId: 103, courseTitle: "UX/UI Design", courseOverallProgress: 0, chaptersCompleted: 0, totalChapters: 6 },
    ]
  },
  { 
    id: "usr_2", 
    name: "Bob Martin", 
    email: "bob.martin@example.com", 
    coursesEnrolled: 2, 
    coursesCompleted: 2, 
    overallProgress: 100,
    courses: [
      { courseId: 101, courseTitle: "Introduction au Dev Web", courseOverallProgress: 100, chaptersCompleted: 4, totalChapters: 4 },
      { courseId: 104, courseTitle: "Data Science avec R", courseOverallProgress: 100, chaptersCompleted: 7, totalChapters: 7 },
    ]
  },
  { 
    id: "usr_3", 
    name: "Charlie Durand", 
    email: "charlie.durand@example.com", 
    coursesEnrolled: 4, 
    coursesCompleted: 0, 
    overallProgress: 12,
    courses: [
      { courseId: 101, courseTitle: "Introduction au Dev Web", courseOverallProgress: 10, chaptersCompleted: 1, totalChapters: 4 },
      { courseId: 105, courseTitle: "Cloud Computing AWS", courseOverallProgress: 5, chaptersCompleted: 1, totalChapters: 20 },
      { courseId: 106, courseTitle: "Cybersecurite", courseOverallProgress: 0, chaptersCompleted: 0, totalChapters: 10 },
      { courseId: 102, courseTitle: "Bases de Python", courseOverallProgress: 0, chaptersCompleted: 0, totalChapters: 5 },
    ]
  },
  { 
    id: "usr_4", 
    name: "Diana Petit", 
    email: "diana.petit@example.com", 
    coursesEnrolled: 1, 
    coursesCompleted: 0, 
    overallProgress: 0,
    courses: [
      { courseId: 103, courseTitle: "UX/UI Design", courseOverallProgress: 0, chaptersCompleted: 0, totalChapters: 6 },
    ]
  },
  { 
    id: "usr_5", 
    name: "Ethan Lefebvre", 
    email: "ethan.lefebvre@example.com", 
    coursesEnrolled: 2, 
    coursesCompleted: 1, 
    overallProgress: 66,
    courses: [
      { courseId: 104, courseTitle: "Data Science avec R", courseOverallProgress: 100, chaptersCompleted: 7, totalChapters: 7 },
      { courseId: 106, courseTitle: "Cybersecurite", courseOverallProgress: 30, chaptersCompleted: 3, totalChapters: 10 },
    ]
  },
  { 
    id: "usr_6", 
    name: "Fiona Girard", 
    email: "fiona.girard@example.com", 
    coursesEnrolled: 1, 
    coursesCompleted: 0, 
    overallProgress: 50,
    courses: [
      { courseId: 105, courseTitle: "Cloud Computing AWS", courseOverallProgress: 50, chaptersCompleted: 10, totalChapters: 20 },
    ]
  },
  { 
    id: "usr_7", 
    name: "Gael Rousseau", 
    email: "gael.rousseau@example.com", 
    coursesEnrolled: 3, 
    coursesCompleted: 2, 
    overallProgress: 71,
    courses: [
      { courseId: 101, courseTitle: "Introduction au Dev Web", courseOverallProgress: 100, chaptersCompleted: 4, totalChapters: 4 },
      { courseId: 102, courseTitle: "Bases de Python", courseOverallProgress: 100, chaptersCompleted: 5, totalChapters: 5 },
      { courseId: 103, courseTitle: "UX/UI Design", courseOverallProgress: 20, chaptersCompleted: 1, totalChapters: 6 },
    ]
  },
]

/**
 * Fetches aggregated learner progress data.
 * In a real-world scenario, this would make an API call to a dedicated backend endpoint.
 * For now, it simulates a network request and returns mock data.
 * @returns A promise that resolves to an array of LearnerProgress objects.
 */
const getLearnerProgress = (): Promise<LearnerProgress[]> => {
  console.log("AnalyticsService: Fetching learner progress data...");
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log("AnalyticsService: Data fetched successfully.");
      resolve(mockData)
    }, 1200) // Simulate network delay
  })
}

/**
 * Fetches the main dashboard summary statistics for an admin.
 * @returns A promise that resolves to the dashboard summary data.
 */
const getDashboardSummary = async (): Promise<AdminDashboardSummary> => {
    const response = await fetchApi<any>("/dashboard/summary", { method: "GET" });
    if (response && response.data && response.data.mode === 'ADMIN') {
        return response.data;
    } else {
        throw new Error("Invalid API response format for dashboard summary.");
    }
}


// Export the service methods
export const analyticsService = {
  getLearnerProgress,
  getDashboardSummary,
}
